In [1]:
# Soru 1 – Liste Metotları

notlar = [85, 92, 76, 92, 100, 76, 85, 92]

# Benzersiz liste
benzersiz = list(set(notlar))
print("Benzersiz:", benzersiz)

# En yüksek ve en düşük not
print("En yüksek:", max(notlar))
print("En düşük:", min(notlar))

# Küçükten büyüğe sıralama
sirali = sorted(benzersiz)
print("Sıralı:", sirali)


Benzersiz: [100, 92, 85, 76]
En yüksek: 100
En düşük: 76
Sıralı: [76, 85, 92, 100]


In [2]:
# Soru 2 – Sayılar

def armstrong_mu(sayi):
    return sum(int(h)**3 for h in str(sayi)) == sayi

print(153, "Armstrong mu?", armstrong_mu(153))
print(123, "Armstrong mu?", armstrong_mu(123))


153 Armstrong mu? True
123 Armstrong mu? False


In [3]:
# Soru 3 – Kümeler

A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

print("Ortak:", A & B)
print("Sadece A’da:", A - B)
print("Birleşim:", sorted(A | B))


Ortak: {'Python', 'SQL'}
Sadece A’da: {'Java', 'R'}
Birleşim: ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [4]:
# Soru 4 – Modüller

import random, statistics

sayilar = [random.randint(1, 100) for _ in range(10)]
print("Sayılar:", sayilar)
print("Ortalama:", statistics.mean(sayilar))
print("Std sapma:", statistics.pstdev(sayilar))


Sayılar: [17, 9, 33, 45, 67, 94, 77, 58, 36, 13]
Ortalama: 44.9
Std sapma: 27.21562051469707


In [5]:
# Soru 5 – Fonksiyonlar

from collections import Counter

def kelime_sayaci(metin):
    kelimeler = metin.split()
    toplam = len(kelimeler)
    en_uzun = max(kelimeler, key=len)
    en_sik = Counter(kelimeler).most_common(1)[0][0]
    return toplam, en_uzun, en_sik

print(kelime_sayaci("veri bilim veri analiz python veri"))


(6, 'analiz', 'veri')


In [6]:
# Soru 6 – Gömülü Fonksiyonlar


sayilar = [5, 12, 7, 18, 24, 3, 16]

ciftler = list(filter(lambda x: x % 2 == 0, sayilar))
kareler = list(map(lambda x: x**2, ciftler))
sirali = sorted(kareler, reverse=True)

print("Çiftler:", ciftler)
print("Kareler:", kareler)
print("Azalan kareler:", sirali)


Çiftler: [12, 18, 24, 16]
Kareler: [144, 324, 576, 256]
Azalan kareler: [576, 324, 256, 144]


In [7]:
# Soru 7 – Lambda İfadeleri


kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]

sirali = sorted(kelimeler, key=lambda x: len(x))
print("Sıralı:", sirali)


Sıralı: ['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [8]:
# Soru 8 – Metodlar


def rakam_toplam(metin):
    sayilar = [int(ch) for ch in metin if ch.isdigit()]
    return sum(sayilar)

print(rakam_toplam("abc12def3"))  # 1+2+3=6


6


In [10]:
# Soru 9 – (Ekstra) Numpy 1 

import numpy as np

dizi = np.random.randint(0, 51, 10)
print("Dizi:", dizi)
print("Ortalama:", np.mean(dizi))
print("Std sapma:", np.std(dizi))
print("Max:", np.max(dizi))


Dizi: [44  9 40 14 37 45 14  1 14 48]
Ortalama: 26.6
Std sapma: 16.817847662528045
Max: 48


In [11]:
# Soru 10 – (Ekstra) Numpy 2

matris = np.random.rand(5, 5)
print("Matris:\n", matris)

print("Sütun ortalamaları:", matris.mean(axis=0))

binary = (matris > 0.5).astype(int)
print("Binary matris:\n", binary)


Matris:
 [[0.99764812 0.93176183 0.7361935  0.02667344 0.97741194]
 [0.9846107  0.38237316 0.50919886 0.6288472  0.52293245]
 [0.92123327 0.79691627 0.2211711  0.47258019 0.31830151]
 [0.40828652 0.44599455 0.91330343 0.40312963 0.02618051]
 [0.15942353 0.52744257 0.52484786 0.78397826 0.50078939]]
Sütun ortalamaları: [0.69424043 0.61689768 0.58094295 0.46304174 0.46912316]
Binary matris:
 [[1 1 1 0 1]
 [1 0 1 1 1]
 [1 1 0 0 0]
 [0 0 1 0 0]
 [0 1 1 1 1]]
